### ISSUE TITLE
injected router not passed to child-components?

### ISSUE THREAD

**Issue by doppelreim** [vuejs/vue-test-utils#679]
### Version
1.0.0-beta.16

### Reproduction link
[https://github.com/doppelreim/vue-test-app/tree/test-route-in-child](https://github.com/doppelreim/vue-test-app/tree/test-route-in-child)

### Steps to reproduce
Run `./node_modules/.bin/vue-cli-service test:unit`

### What is expected?
The test should not explode.

### What is actually happening?
It does explode.

Error:
```
 HelloWorld.vue
[Vue warn]: Error in config.errorHandler: "TypeError: Cannot read property 'query' of undefined"
TypeError: Cannot read property 'query' of undefined
```

---
The test tests HelloWorld.vue

HelloWorld.vue includes a child-component (TheChild.vue)

TheChild makes use of the router.

In the test, I inject a router-mock into the localvue.

My best guess is, that the injected routerMock is visible only in the component under test, and it is somehow not visible in the child-component?

(This is the same problem as #591 - that ticket was closed, but the issue is still there and I can not reopen it)

**Comment by doppelreim** [comment]
I updated vue-test-utils to `beta18` and vue to `beta15`
The issue still persists, though :/

**Comment by eddyerburgh** [comment]
This should be fixed in beta.19

**Comment by doppelreim** [comment]
@eddyerburgh 
I updated `vue-test-utils` to `beta19`.
The issue still persists, though :/
